# routes
route_presets:
  webframe_route: &webframe_route
    path: "/web/:url?"
    name: "webframe"
    component: WebFrame
    props: true
  applet_launcher_route: &applet_launcher_route
    path: "/applet/:applet?"
    name: "applet-launcher"
    component: AppletLauncher
    props: true
  model_viewer_route: &model_viewer_route
    path: "/models/:model_src?/:info?"
    name: "model-viewer"
    component: ModelViewer3D
    props: true
  package_explorer_route: &package_explorer_route
    path: "/package/:content?"
    name: "package-explorer"
    component: PackageExplorer
    props: true
# applets
applets:
  - route:
      path: "/"
      name: "home"
      component: Home
    tags: []
    category: ["service"]
    title: ""

  - route: *webframe_route
    tags: []
    title: ""

  - route:
      path: "/applets/:query?"
      name: "applets-catalog"
      component: AppletsCatalog
      props: true
    tags: ["service"]
    category: ["service"]
    title: ""

  - route: *webframe_route
    tags: ["extras", "experiment", "voxels", "procedural", "three"]
    title: "Brickscape [Demo]"
    category: ["project", "demo"]
    preview: "assets/preview/hexworld_a1.png"
    summary: "assets/docs/brickscape.txt"
    props:
      url: "https://sanyabeast.github.io/brickscape/dist/index.html"

  - route: *webframe_route
    tags: ["game", "old"]
    title: "Match3"
    category: ["project"]
    preview: "assets/preview/match3_a1.png"
    summary: "assets/docs/match3.txt"
    props:
      url: "https://sanyabeast.github.io/match3/"

  - route: *webframe_route
    tags: ["game", "old"]
    title: "Forest Lads [Demo]"
    category: ["project", "demo"]
    preview: "assets/preview/forestlads_a1.png"
    props:
      url: "https://sanyabeast.github.io/forestlads/dist/index.html"

  - route: *webframe_route
    tags: ["game", "old"]
    title: "Telechart"
    summary: "assets/docs/telechart.txt"
    preview: "assets/preview/telechart_a1.png"
    props:
      url: "https://sanyabeast.github.io/telechart/"

  - route: *webframe_route
    tags: ["game", "old"]
    title: "Hill Rider [Demo]"
    category: ["demo"]
    summary: "assets/docs/hillrider.txt"
    preview: "assets/preview/coderider_a1.png"
    props:
      url: "https://sanyabeast.github.io/coderider/dist/index.html"

  - route: *webframe_route
    tags: ["extras", "game", "engine"]
    title: "Retro Engine [Demo]"
    category: ["demo"]
    preview: "assets/preview/retro_engine_a1.png"
    props:
      url: "https://sanyabeast.github.io/retro/dist/demo_alt/"

  - route: *webframe_route
    tags: ["extras", "experiment"]
    title: "Euphoria [Demo]"
    category: ["lab"]
    preview: "assets/preview/euphoria_da1.png"
    props:
      url: "https://sanyabeast.github.io/euphoria/dist/index.html"
    is_extra: true

  - route: *webframe_route
    tags: ["extras", "commercial", "chart", "plot", "three", "gl"]
    category: ["project"]
    title: "Plot3 [Demo]"
    preview: "assets/preview/plot_a1.png"
    props:
      url: "projects/plot/index.html"

  - route: *webframe_route
    tags: ["extras", "retro", "unity", "game"]
    category: ["project"]
    title: "Middlenight [Demo]"
    summary: "assets/docs/middlenight.txt"
    preview: "assets/preview/middlenight_a1.png"
    props:
      url: "projects/middlenight/index.html"

  - route:
      path: "/applet/polar-picture-tool/:image"
      name: "applet/polar-picture-tool"
      component: PolarPictureTool
      props: true
    summary: "assets/docs/polar_picture_tool.txt"
    tags: ["three", "gl", "tool", "shader", "utils", "image"]
    category: ["project", "experiment"]
    title: "Polar Picture Tool"
    preview: "assets/preview/polar_image_a1.png"
    props:
      image: "random"

  - route: *applet_launcher_route
    tags: []
    category: ["service"]
    title: "Applet Launcher"
    props: {}

  - route: *model_viewer_route
    tags: []
    category: ["three", "gl", "model", "viewer"]
    title: "Model Viewer"
    document: "assets/docs/showdown.md"
    props:
      model_src: "assets/models/suzanne/Suzanne.gltf"
      info: "assets/models/suzanne/README.md"

  - route: *package_explorer_route
    tags: ["service", "utils", "file"]
    category: []
    title: "Directory Explorer"
    props:
      content:
        title: "Sample Directory"
        summary: "assets/docs/telechart.txt"
        avatar: "assets/image/pattern.png"
        files:
          - ["Readme", "sample.txt"]
          - ["Readme2", "sample2.txt"]
          - ["Personal Photo 1", "pic01.jpg"]
          - ["Personal Photo 2", "pic02.jpg"]
