shaders:
  sample:
    fragment: assets/shader/sample.frag
    vertex: assets/shader/fullscreen_plane.vert
    uniforms:
      u_time: 0
      u_mouse: [0, 0]
      u_resolution: [1, 1]
      u_color: [1, 0, 0]
  polar_picture_tool:
    fragment: assets/shader/polar_picture_tool.frag
    vertex: assets/shader/fullscreen_plane.vert
    uniforms:
      u_map: null
      u_mode: 0
      u_offset: [0, 0]
      u_scale: [1, 1]
  starscape:
    fragment: assets/shader/starscape.frag
    vertex: assets/shader/fullscreen_plane.vert
    uniforms:
      u_time: 0
      u_mouse: [0, 0]
      u_resolution: [1, 1]
      u_color: [1, 0, 0]

  arctic_lights:
    fragment: assets/shader/arctic_lights.frag
    vertex: assets/shader/fullscreen_plane.vert
    uniforms:
      u_time: 0
      u_mouse: [0, 0]
      u_resolution: [1, 1]
      u_color: [1, 0, 0]

packages:
  sample:
    title: "Sample Directory"
    summary: "assets/docs/telechart.txt"
    avatar: "assets/image/pattern.png"
    files:
      - ["Readme", "sample.txt"]
      - ["Readme2", "sample2.txt"]
      - ["Personal Photo 1", "pic01.jpg"]
      - ["Personal Photo 2", "pic02.jpg"]
# web-frame urls
urls:
  brickscape: https://sanyabeast.github.io/brickscape/dist/index.html
  match3: https://sanyabeast.github.io/match3/
  forestlads: https://sanyabeast.github.io/forestlads/dist/index.html
  telechart: https://sanyabeast.github.io/telechart/
  coderider: https://sanyabeast.github.io/coderider/dist/index.html
  retro_engine_demo: https://sanyabeast.github.io/retro/dist/demo_alt/
  euphoria_demo: https://sanyabeast.github.io/euphoria/dist/index.html
  plot3: projects/plot/index.html
  middlenight: projects/middlenight/index.html
# route presets
route_presets:
  webframe_route: &webframe_route
    path: "/web/:url?"
    name: "webframe"
    component: WebFrame
    props: true
  applet_launcher_route: &applet_launcher_route
    path: "/applet/:applet?"
    name: "applet-launcher"
    component: AppletLauncher
    props: true
  model_viewer_route: &model_viewer_route
    path: "/models/:model_src?/:info?"
    name: "model-viewer"
    component: ModelViewer3D
    props: true
  package_explorer_route: &package_explorer_route
    path: "/package/:package_id"
    name: "package-explorer"
    component: PackageExplorer
    props: true
# applets
applets:
  - route:
      path: "/"
      name: "home"
      component: Home
    tags: []
    category: ["service"]
    summary: assets/docs/about.txt
    title: "About"

  - route: *webframe_route
    tags: []
    title: ""

  - route:
      path: "/applets/:query?"
      name: "applets-catalog"
      component: AppletsCatalog
      props: true
    tags: ["service"]
    summary: assets/docs/applets-catalog.txt
    category: ["service"]
    title: "Applets"

  - route: *webframe_route
    tags: ["extras", "experiment", "voxels", "procedural", "three"]
    title: "Brickscape [Demo]"
    category: ["project", "demo"]
    document: "assets/docs/brickscape.md"
    preview: "assets/preview/hexworld_a1.png"
    summary: "assets/docs/brickscape.txt"
    props:
      url: brickscape

  - route: *webframe_route
    tags: ["game", "old"]
    title: "Match3"
    category: ["project"]
    preview: "assets/preview/match3_a1.png"
    summary: "assets/docs/match3.txt"
    props:
      url: match3

  - route: *webframe_route
    tags: ["game", "old"]
    title: "Forest Lads [Demo]"
    category: ["project", "demo"]
    preview: "assets/preview/forestlads_a1.png"
    props:
      url: forestlads

  - route: *webframe_route
    tags: ["game", "old"]
    title: "Telechart"
    summary: "assets/docs/telechart.txt"
    preview: "assets/preview/telechart_a1.png"
    props:
      url: telechart

  - route: *webframe_route
    tags: ["game", "old"]
    title: "Hill Rider [Demo]"
    category: ["demo"]
    summary: "assets/docs/hillrider.txt"
    preview: "assets/preview/coderider_a1.png"
    props:
      url: coderider

  - route: *webframe_route
    tags: ["extras", "game", "engine"]
    title: "Retro Engine [Demo]"
    category: ["demo"]
    preview: "assets/preview/retro_engine_a1.png"
    props:
      url: retro_engine_demo

  - route: *webframe_route
    tags: ["extras", "experiment"]
    title: "Euphoria [Demo]"
    category: ["lab"]
    preview: "assets/preview/euphoria_da1.png"
    props:
      url: euphoria_demo
    is_extra: true

  - route: *webframe_route
    tags: ["extras", "commercial", "chart", "plot", "three", "gl"]
    category: ["project"]
    title: "Plot3 [Demo]"
    summary: "assets/docs/plot3.txt"
    document: "assets/docs/plot3.md"
    preview: "assets/preview/stonks_a1.png"
    props:
      url: plot3

  - route: *webframe_route
    tags: ["extras", "retro", "unity", "game"]
    category: ["project"]
    title: "Middlenight [Demo]"
    summary: "assets/docs/middlenight.txt"
    preview: "assets/preview/middlenight_a1.png"
    props:
      url: middlenight

  - route:
      path: "/applet/polar-picture-tool/:image"
      name: "applet/polar-picture-tool"
      component: PolarPictureTool
      props: true
    summary: "assets/docs/polar_picture_tool.txt"
    tags: ["three", "gl", "tool", "shader", "utils", "image"]
    category: ["project", "experiment"]
    title: "Polar Picture Tool"
    preview: "assets/preview/polar_image_a1.png"
    props:
      image: "random"

  - route: *applet_launcher_route
    tags: []
    category: ["service"]
    title: "Applet Launcher"
    props: {}

  - route: *model_viewer_route
    tags: ["service"]
    category: ["service"]
    title: "Model Viewer"
    summary: "assets/docs/model-viewer.txt"
    document: "assets/docs/model-viewer.md"
    props:
      model_src: "assets/models/suzanne/Suzanne.gltf"
      info: "assets/models/suzanne/README.md"

  - route: *package_explorer_route
    tags: ["service"]
    category: ["service"]
    title: "Package Explorer"
    props:
      package_id: sample

  - route:
      path: "/shader/:shader_id"
      name: "applet/shader-view"
      component: ShaderView
      props: true
    tags: ["service"]
    category: ["service"]
    title: "ShaderView"
    props:
      shader_id: starscape
