shaders:
  sample:
    fragment: assets/shader/sample.frag
    vertex: assets/shader/fullscreen_plane.vert
    uniforms:
      u_color: [1, 0, 0]
  polar_picture_tool:
    fragment: assets/shader/polar_picture_tool.frag
    vertex: assets/shader/fullscreen_plane.vert
    uniforms:
      u_map: null
      u_mode: 0
      u_offset: [0, 0]
      u_scale: [1, 1]
  starscape:
    fragment: assets/shader/starscape.frag
    vertex: assets/shader/fullscreen_plane.vert
    uniforms:
      u_color: [1, 0, 0]

  arctic_lights:
    fragment: assets/shader/arctic_lights.frag
    vertex: assets/shader/fullscreen_plane.vert
    uniforms:
      u_color: [1, 0, 0]

  retroid_maker:
    fragment: assets/shader/retroid.frag
    vertex: assets/shader/fullscreen_plane.vert
    uniforms:
      u_map: "assets/image/uv_checker_001.jpg"

# web-frame urls
urls:
  brickscape: https://sanyabeast.github.io/brickscape/dist/index.html
  match3: https://sanyabeast.github.io/match3/
  forestlads: https://sanyabeast.github.io/forestlads/dist/index.html
  telechart: https://sanyabeast.github.io/telechart/
  coderider: https://sanyabeast.github.io/coderider/dist/index.html
  retro_engine_demo: https://sanyabeast.github.io/retro/dist/demo_alt/
  euphoria_demo: https://sanyabeast.github.io/euphoria/dist/index.html
  plot3: projects/plot/index.html
  middlenight: projects/middlenight/index.html
  random_wikipedia: https://en.wikipedia.org/wiki/Special:Random
  mailto: mailto:a.gvrnsk@gmail.com?subject=chronicle

packages:
  sample:
    - ["Readme", "sample.txt"]
    - ["Readme2", "sample2.md"]
    - ["Personal Photo 1", "pic01.jpg"]
    - ["Personal Photo 2", "pic02.png"]
    - ["Personal Video 3", "pic03.mp4"]
    - ["Personal Video 4", "pic04.webm"]
    - ["Personal Audio 5", "pic05.mp3"]
    - ["Some File", "pic02"]
    - [github, https://github.com/sanyabeast/brickscape]
    - [mail, mailto:a.gvrnsk@gmail.com?subject=chronicle]
  brickscape:
    - [source code, https://github.com/sanyabeast/brickscape]

# route presets
route_presets:
  about_route: &about_route
    path: "/"
    name: "about"
    component: AboutPage
  webframe_route: &webframe_route
    path: "/web/:url?"
    name: "webframe"
    component: WebFrame
    props: true
  applet_launcher_route: &applet_launcher_route
    path: "/applet-info/:applet?"
    name: "applet-launcher"
    component: AppletLauncher
    props: true
  model_viewer_route: &model_viewer_route
    path: "/models/:model_src?/:info?"
    name: "model-viewer"
    component: ModelViewer3D
    props: true
# applets
applets:
  - route: *about_route
    tags: []
    category: ["service"]
    summary: assets/docs/about.txt
    preview: assets/pimp_002.png
    package:
      - [github profile, https://github.com/sanyabeast]
      - [e-mail, mailto:a.gvrnsk@gmail.com?subject=chronicle]
      - [linkedin, https://www.linkedin.com/in/sanyabeast/]
      - [sketchfab, https://sketchfab.com/sanchibbo/models]
      - [source code of this site, https://github.com/sanyabeast/chronicle]
    title: "About"

  - route: *webframe_route
    tags: []
    title: "The Internet"
    category: ["service"]
    props:
      url: random_wikipedia

  - route:
      path: "/applets/:query?"
      name: "applets-catalog"
      component: AppletsCatalog
      props: true
    tags: ["service"]
    summary: assets/docs/applets-catalog.txt
    category: ["service"]
    title: "Applets"

  - route: *applet_launcher_route
    tags: []
    category: []
    title: "Applet Launcher"
    props: {}

  - route: *webframe_route
    tags: ["extras", "experiment", "voxels", "procedural", "three"]
    title: "Brickscape [Demo]"
    category: ["project", "demo"]
    document: "assets/docs/brickscape.md"
    preview: "assets/preview/hexworld_a1.png"
    summary: "assets/docs/brickscape.txt"
    package: brickscape
    props:
      url: brickscape

  - route: *webframe_route
    tags: ["game", "old"]
    title: "Match3"
    category: ["project"]
    preview: "assets/preview/match3_a1.png"
    summary: "assets/docs/match3.txt"
    document: "assets/docs/match3.md"
    package:
      - [source code, https://github.com/sanyabeast/match3]
    props:
      url: match3

  - route: *webframe_route
    tags: ["game", "old"]
    title: "Forest Lads [Demo]"
    category: ["project", "demo"]
    preview: "assets/preview/forestlads_a1.png"
    props:
      url: forestlads

  - route: *webframe_route
    tags: ["game", "old"]
    title: "Telechart"
    summary: "assets/docs/telechart.txt"
    preview: "assets/preview/telechart_a1.png"
    props:
      url: telechart

  - route: *webframe_route
    tags: ["game", "old"]
    title: "Hill Rider [Demo]"
    category: ["demo"]
    summary: "assets/docs/hillrider.txt"
    preview: "assets/preview/coderider_a1.png"
    props:
      url: coderider

  - route: *webframe_route
    tags: ["extras", "game", "engine"]
    title: "Retro Engine [Demo]"
    category: ["demo"]
    preview: "assets/preview/retro_engine_a1.png"
    props:
      url: retro_engine_demo

  - route: *webframe_route
    tags: ["extras", "experiment"]
    title: "Euphoria [Demo]"
    category: ["lab"]
    preview: "assets/preview/euphoria_da1.png"
    props:
      url: euphoria_demo
    is_extra: true

  - route: *webframe_route
    tags: ["extras", "commercial", "chart", "plot", "three", "gl"]
    category: ["project"]
    title: "Plot3 [Demo]"
    summary: "assets/docs/plot3.txt"
    document: "assets/docs/plot3.md"
    preview: "assets/preview/stonks_a1.png"
    props:
      url: plot3

  - route: *webframe_route
    tags: ["extras", "retro", "unity", "game"]
    category: ["project"]
    title: "Middlenight [Demo]"
    summary: "assets/docs/middlenight.txt"
    preview: "assets/preview/middlenight_a1.png"
    props:
      url: middlenight

  - route:
      path: "/applet/polar-picture-tool/:image"
      name: "applet/polar-picture-tool"
      component: PolarPictureTool
      props: true
    summary: "assets/docs/polar_picture_tool.txt"
    tags: ["three", "gl", "tool", "shader", "utils", "image"]
    category: ["project", "experiment"]
    title: "Polar Picture Tool"
    preview: "assets/preview/polar_image_a1.png"
    props:
      image: "random"

  - route: *model_viewer_route
    tags: ["service"]
    category: ["service"]
    title: "3D Model View"
    summary: "assets/docs/model-viewer.txt"
    document: "assets/docs/model-viewer.md"
    props:
      model_src: "assets/models/suzanne/Suzanne.gltf"
      info: "assets/models/suzanne/README.md"

  - route: *about_route
    tags: ["service"]
    category: ["service"]
    preview: "assets/image/pattern.png"
    summary: "assets/docs/model-viewer.txt"
    document: "assets/docs/model-viewer.md"
    title: "Packages Example"
    package: sample

  - route:
      path: "/shader/:shader_id"
      name: "applet/shader-view"
      component: ShaderView
      props: true
    tags: ["service"]
    category: ["service"]
    title: "Shader View"
    props:
      shader_id: starscape

  - route: *about_route
    tags:
      [
        "project",
        "3d",
        "three",
        "gl",
        "application",
        "windows",
        "macos",
        "linux",
      ]
    category: ["package"]
    title: "preview3d"
    preview: "assets/preview/preview3d_01.png"
    summary: "assets/docs/preview3d.txt"
    package:
      - [releases, https://github.com/sanyabeast/preview_3d/releases]
      - [
          windows,
          https://github.com/sanyabeast/preview_3d/releases/download/1.0.11/preview_3d.Setup.1.0.11.exe,
        ]
      - [
          macos,
          https://github.com/sanyabeast/preview_3d/releases/download/1.0.11/preview_3d-1.0.11.dmg,
        ]
      - [source code, https://github.com/sanyabeast/preview_3d]

  - route: *about_route
    tags: ["article", "psp2", "psvita", "playstation", "homebrew", "unity"]
    category: ["article"]
    title: "PSP2 Unity Homebrew Development"
    document: "assets/articles/psp2dev.md"
    package:
      - [
          SDK,
          https://drive.google.com/file/d/19qK0DQi0L0-NS5-N939Ky3HzNskRVyEZ/view?usp=sharing,
        ]
      - [
          Unity Editor,
          https://unity.com/releases/editor/archive#download-archive-2019,
        ]
      - [Vita Support for Unity, https://archive.org/details/unitypsvitasupport]
      - [Silica's VPK Tool, assets/misc/SilicaVPK.py]
      - [Patcher, https://www.google.com/search?q=UniPatcher2018_v1.exe]

  - route:
      name: "RetroidMaker"
      path: "/applet/retroid-maker"
      component: RetroidMaker
      props: true
    tags: ["experiment", "game", "three", "gl", "shader", "utils"]
    category: ["experiment"]
    title: "Retroid Maker"
    preview: "assets/image/pattern.png"

  - route:
      name: "MazeGenerator"
      path: "/applet/maze-generator"
      component: MazeGenerator
      props: true
    tags: ["experiment", "utils", "canvas2d", "algorithm"]
    category: ["experiment"]
    summary: "assets/docs/maze_generator.txt"
    document: "assets/docs/maze_generator.md"
    title: "Maze Generator"
    preview: "assets/preview/maze_generator.png"
