# routes
route_presets:
  webframe_route: &webframe_route
    path: "/web-frame/:url?"
    name: "web-frame"
    component: WebFrame
    props: true
  applet_launcher_route: &applet_launcher_route
    path: "/applet-launcher/:applet?"
    name: "applet/applet-launcher"
    component: AppletLauncher
    props: true
  model_viewer_route: &model_viewer_route
    path: "/model_viewer/:model_src?/:info?"
    name: "applet/model_viewer"
    component: ModelViewer3D
    props: true
# applets
applets:
  - route:
      path: "/"
      name: "home"
      component: Home
    tags: []
    title: ""
    service: true

  - route: *webframe_route
    tags: []
    title: ""
    service: true

  - route:
      path: "/search-result/:query?"
      name: "search-result"
      component: SearchResult
      props: true
    tags: []
    title: ""
    service: true

  - route: *webframe_route
    tags: ["extras", "experiment", "voxels", "procedural", "three"]
    title: "Brickscape [Demo]"
    preview: "assets/preview/hexworld_a1.png"
    summary: "assets/docs/brickscape.txt"
    props:
      url: "https://sanyabeast.github.io/brickscape/dist/index.html"

  - route: *webframe_route
    tags: ["game", "old"]
    title: "Match3"
    preview: "assets/preview/match3_a1.png"
    summary: "assets/docs/match3.txt"
    props:
      url: "https://sanyabeast.github.io/match3/"

  - route: *webframe_route
    tags: ["game", "old"]
    title: "Forest Lads [Demo]"
    preview: "assets/preview/forestlads_a1.png"
    props:
      url: "https://sanyabeast.github.io/forestlads/dist/index.html"

  - route: *webframe_route
    tags: ["game", "old"]
    title: "Telechart"
    summary: "assets/docs/telechart.txt"
    preview: "assets/preview/telechart_a1.png"
    props:
      url: "https://sanyabeast.github.io/telechart/"

  - route: *webframe_route
    tags: ["game", "old"]
    title: "Hill Rider [Demo]"
    summary: "assets/docs/hillrider.txt"
    preview: "assets/preview/coderider_a1.png"
    props:
      url: "https://sanyabeast.github.io/coderider/dist/index.html"

  - route: *webframe_route
    tags: ["extras", "game", "engine"]
    title: "Retro Engine [Demo]"
    preview: "assets/preview/retro_engine_a1.png"
    props:
      url: "https://sanyabeast.github.io/retro/dist/demo_alt/"

  - route: *webframe_route
    tags: ["extras", "experiment"]
    title: "Euphoria [Demo]"
    preview: "assets/preview/euphoria_da1.png"
    props:
      url: "https://sanyabeast.github.io/euphoria/dist/index.html"
    is_extra: true

  - route: *webframe_route
    tags: ["extras", "commercial", "chart", "plot", "three", "gl"]
    title: "Plot3 [Demo]"
    preview: "assets/preview/plot_a1.png"
    props:
      url: "projects/plot/index.html"

  - route: *webframe_route
    tags: ["extras", "retro", "unity", "game"]
    title: "Middlenight [Demo]"
    summary: "assets/docs/middlenight.txt"
    preview: "assets/preview/middlenight_a1.png"
    props:
      url: "projects/middlenight/index.html"

  - route:
      path: "/applet/polar-picture-tool/:image"
      name: "applet/polar-picture-tool"
      component: PolarPictureTool
      props: true
    summary: "assets/docs/polar_picture_tool.txt"
    tags: ["experiment", "tool", "image", "polar", "math", "three", "gl"]
    title: "Polar Picture Tool"
    preview: "assets/preview/polar_image_a1.png"
    props:
      image: "random"

  - route: *applet_launcher_route
    tags: ["service"]
    title: "Applet Launcher"
    props: {}
    service: true

  - route: *model_viewer_route
    tags: ["service"]
    title: "Model Viewer"
    document: "assets/docs/showdown.md"
    props:
      model_src: 'assets/models/suzanne/Suzanne.gltf'
      info: 'assets/models/suzanne/README.md'
    service: true
